include $(GOROOT)/src/Make.inc

TARG = mudkip/lib
GOFILES = errors.go message.go messages/*.go game/*.go game/components/*.go \
	data/*.go builder/*.go
CLEANFILES += *.js

include $(GOROOT)/src/Make.pkg
