
all:
	make -C mongo install
	make -C mysql install
	make -C sqlite install

clean:
	make -C mongo clean
	make -C mysql clean
	make -C sqlite clean

test:
	make -C mongo test
	make -C mysql test
	make -C sqlite test

